name: Joanne's Website
description: Ramblings
meta_description: ""

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl:
domain_name: "http://joanne.soy"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Joanne Lee"

# Disqus config
disqus-shortname: ""
